jobs:
  include:
    language: python
    python:
      - 3.6
      - 3.7
      - 3.8
      - 3.9
    # command to install dependencies
    before_install:
      - pip install --upgrade pip
      - pip install codecov
    install:
      - pip install tox-travis
    # command to run tests
    script:
      - tox -e black,flake8
      - tox
    after_script:
      - git push origin HEAD:$TRAVIS_PULL_REQUEST_BRANCH
    after_success:
      - codecov
notifications:
  email: false
