jobs:
  include:
    language: python
    matrix:
      fast_finish: true
      include:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    # command to install dependencies
    before_install:
      - pip install --upgrade pip
    install:
      - pip install tox-travis
    # command to run tests
    script:
      - tox -e black,flake8
      - tox
      - git push origin HEAD:$TRAVIS_PULL_REQUEST_BRANCH
notifications:
  email: false
